package lts.main.input_preprocessing;

/**This is generated by StringToIntEncoder. It provides reverse operations, decoding ints back to their String ids and labels.
 * Updating the parent StringToIntEncoder instance after generating IntToStringDecoder will invalidate it.
 */
public class IntToStringDecoder {

	private final String[] graphIds, nodeLabels, edgeLabels;
	private final String[][] nodeIdsForGraphs;
	
	protected IntToStringDecoder(String[] graphIds, String[] nodeLabels, String[] edgeLabels, String[][] nodeIdsForGraphs) {
		this.graphIds = graphIds;
		this.nodeLabels = nodeLabels;
		this.edgeLabels = edgeLabels;
		this.nodeIdsForGraphs = nodeIdsForGraphs;
	}

	public String decodeGraphId(int graphIdInt) {
		return graphIds[graphIdInt];
	}

	public String decodeNodeLabel(int nodeLabelInt) {
		return nodeLabels[nodeLabelInt];
	}

	public String decodeEdgeLabel(int edgeLabelInt) {
		return edgeLabels[edgeLabelInt];
	}

	public String decodeNodeIdForGraphs(int graphIdInt, int nodeIdInt) {
		return nodeIdsForGraphs[graphIdInt][nodeIdInt];
	}
	
}
